namespace Craftify.DesignAutomationToolkit.Settings.Descriptors.WorkItemExecutionSettingsDescriptorStages;

public interface ICallbackExecutionArgumentsAssignment
{
    ICallbackExecutionArgumentsAssignment WithCallbackBaseUrl(string callbackBaseUrl);
}